### ISSUE TITLE
Garden rendering issues with different resolutions

### ISSUE THREAD

**Issue by libertylocked** [cs1530-group1/garden_app#11]
The circle appears to be in different sizes on different screen resolutions.

Also on 1280x800 (the res of the tablet our user uses), the garden background texture is smaller than the screen, causing the texture to be rendered incorrectly.

![capture_tab](https://cloud.githubusercontent.com/assets/1425794/8315234/1fbd5cb8-19bd-11e5-9e24-e5ecda6a6c85.PNG)

![capture_phone](https://cloud.githubusercontent.com/assets/1425794/8315239/25884bee-19bd-11e5-97a9-3e4af743b472.PNG)

**Comment by chuckie512** [comment]
I have not been able to reproduce this since #58 , unless anyone disagrees I'm going to mark this as closed.
