### ISSUE TITLE
Error Loading Information

### ISSUE THREAD

**Issue by grselker** [cs1530-group1/garden_app#52]
When I open the ViewSpeciesInfo Activity and click the Edit Info button, and then use the back arrow on the menu bar, I get a toast the says Error Loading Information, and all the fields in the ViewSpeciesInfo Activity are blank. LogCat says "Species Info Activity﹕ received a null or empty string, cannot display relevant information". Using the hardware back button does not cause this problem.

**Comment by grselker** [comment]
No actual information is lost, fortunately. If you go back to the SpeciesListActivity and then click on the species, all the original info is still there.

**Comment by chuckie512** [comment]
hmm... I think it may be best just to remove the up button from the menu bar, as the cancel button replaces that functionality.

**Comment by chuckie512** [comment]
That problem would come from that button returning to the previous activity and starting fresh, but there is no way (that i know of or can find) to pass a string with the intent that works with that button.

**Comment by grselker** [comment]
This has been fixed by #54.
