### ISSUE TITLE
Garden engine needs to be refactored

### ISSUE THREAD

**Issue by libertylocked** [cs1530-group1/garden_app#7]
- `boolean StringToGarden(String garden)` should be `static Garden StringToGarden(String garden)`, a factory pattern. This method should not change the state of an already created garden like it is currently doing, but create a new garden.

So one may construct a garden with
`Garden myGarden = Garden.StringToGarden(gardenString);`

For consistency it would also be a good idea to make GardenToString a static method, i.e. `static String GardenToString(Garden garden)`
- Add public getters and setters for the fields in Species and Plant. Also add JUnit tests for those.
- `String[] ListSpecies()` should be changed to `String[] GetSpeciesNames()` to avoid confusion.
- Do not enforce garden string formatting outside of this class. `String GetSpeciesInfo(String species)` is not very usable. I think a good implementation would be `Species GetSpecies(String speciesName)`.

So one may get the species info with
`String sun = myGarden.GetSpecies(myGarden.GetSpeciesNames()[0]).GetSun();`
`int water = myGarden.GetSpecies(myGarden.GetSpeciesNames()[0]).GetWater();`

**Comment by grselker** [comment]
These refactoring items have been corrected. Issue #21 has been created to address some new things.
